[package]
name = "vibes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
rgb = "0.8.37"
textplots = "0.8.4"
